version: '3.9'
services:
  redis:
    container_name: redis
    build: 
      dockerfile: ./Redis.Dockerfile
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
  api-gateway:
    container_name: api-gateway
    build: 
      dockerfile: ./Gateway.Dockerfile
    ports:
      - target: 3000
        published: 30000
        protocol: tcp
        mode: host
    depends_on:
        - redis

  # If we decide to use nginx reverse proxy instead of Node JS socket.io cluster
  #nginx:
  #  container_name: nginx
  #  build: 
  #    dockerfile: ./Nginx.Dockerfile
  #  ports:
  #    - target: 80
  #      published: 3000
  #  depends_on:
  #      - api-gateway