version: '3.9'

services:
  api-gateway:
    container_name: api-gateway
    build: 
      dockerfile: ./Gateway.Dockerfile
    ports:
      - target: 3000
        published: 30000
        protocol: tcp
        mode: host

  redis:
    container_name: redis
    build: 
      dockerfile: ./Redis.Dockerfile
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host

