version: '3.9'
services:
  redis:
    container_name: redis
    build: 
      dockerfile: ./Redis.Dockerfile
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host

  api-gateway:
    container_name: api-gateway
    build: 
      dockerfile: ./Gateway.Dockerfile
    ports:
      - target: 3000
        published: 30000
        protocol: tcp
        mode: host
    depends_on:
        - redis