version: '3.9'

services:
  api-gateway:
    container_name: api-gateway
    build: 
      context: .
    ports:
      - target: 3000
        published: 30000
        protocol: tcp
        mode: host
