version: '1'

services:
  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    
  redis:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"
  redis-slave:
    image: redis:latest
    container_name: redis-slave
    ports:
      - "6380:6379"
    command: redis-server --slaveof master 6379
    depends_on:
      - redis

  store-example:
    build:
      context: .
    container_name: store-example
    links:
      - nats-server
    depends_on:
      - nats-server
    ports:
      - 3000:3000
