version: '3.9'

networks:
  internal-network:
    driver: bridge
    internal: true
  external-network:
    internal: false

services:
  #On external network
  http-producer:
    extends:
      file: examples/HTTPProducer/docker-compose.yml
      service: http-producer
    networks:
      - external-network
    depends_on:
      - api-gateway
      
  socketio-producer:
    extends:
      file: examples/SocketIOProducer/docker-compose.yml
      service: socketio-producer
    networks:
      - external-network
    depends_on:
      - api-gateway

  #Middleware
  api-gateway:
    extends:
      file: api-gateway/docker-compose.yml
      service: api-gateway
    networks:
      - internal-network
      - external-network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - target: 3000
        published: 30000
        protocol: tcp

  #On internal network
  redis:
    image: redis
    networks:
      - internal-network
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
  
  consumer:
    extends:
      file: examples/Consumer/docker-compose.yml
      service: consumer
    networks:
      - internal-network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379