version: '3.9'
services:
  harvest-service:
    extends:
      file: examples/Harvest-server/docker-compose.yml   
      service: harvest-service
    networks:
      - external-network
    ports:
      - target: 3000
        published: 80
        protocol: tcp

  redis:
    image: redis
    networks:
      - internal-network
    ports:
      - target: 6379
        published: 6379
        protocol: tcp

  api-gateway:
    extends:
      file: api-gateway/docker-compose.yml
      service: api-gateway
    networks:
      - internal-network
      - external-network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - target: 3000
        published: 30000
        protocol: tcp
      
  consumer:
    extends:
      file: examples/Consumer/docker-compose.yml
      service: server
    networks:
      - internal-network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  http-producer:
    extends:
      file: examples/HTTPProducer/docker-compose.yml
      service: http-client
    networks:
      - external-network
    depends_on:
      - harvest-service
      - api-gateway
      
  socketio-producer:
    extends:
      file: examples/SocketIOProducer/docker-compose.yml
      service: socketio-client
    networks:
      - external-network
    depends_on:
      - harvest-service
      - api-gateway
      

networks:
  internal-network:
    driver: bridge
    internal: true
  external-network:
    driver: bridge
    internal: false