version: '3.9'

services:
  http-producer:
    container_name: http-producer
    hostname: http-producer
    extends:
      file: examples/HTTPProducer/docker-compose.yml
      service: http-producer
    depends_on:
      - api-gateway
      
  socketio-producer:
    container_name: socketio-producer
    hostname: socketio-producer
    extends:
      file: examples/SocketIOProducer/docker-compose.yml
      service: socketio-producer
    depends_on:
      - api-gateway

  api-gateway:
    container_name: api-gateway
    hostname: api-gateway
    extends:
      file: api-gateway/docker-compose.yml
      service: api-gateway
    depends_on:
      - redis
    #environment:
    # - REDIS_URL= ...
    ports:
      - 30000:3000

  #On internal network
  redis:
    container_name: redis
    hostname: redis
    image: redis
    restart: always
    ports:
      - 6379:6379

  redisinsight:
    container_name: redisinsight
    hostname: redisinsight
    image: redislabs/redisinsight
    depends_on:
      - redis
    ports:
      - 8001:8001
    #environment:
    # - REDIS_URL= ...

  consumer:
    container_name: consumer
    hostname: consumer
    extends:
      file: examples/Consumer/docker-compose.yml
      service: consumer
    depends_on:
      - redis
    #environment:
    # - REDIS_URL= ...