version: '3.9'

services:
  socketio-producer:
    container_name: socketio-producer
    build: 
      context: .
    ports:
      - target: 3000
        published: 30003
        protocol: tcp
        mode: host
