services:
  harvest-service:
    container_name: harvest-server
    build: 
      context: .
    ports:
      - target: 3000
        published: 30000
        protocol: tcp
        mode: host
    environment:
      - FRUITS = ["Strawberry", "Apple", "Banana"]
      - MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]