version: '3.9'
services:
  redis:
    extends: 
      file: ../Redis/docker-compose.yml
      service: redis
      
  harvest-service:
    extends:
      file: Harvest-server/docker-compose.yml
      service: harvest-service

  server:
    extends:
      file: Server/docker-compose.yml
      service: server
    depends_on:
        - redis
  
  client:
    extends:
      file: Client/docker-compose.yml
      service: client
    depends_on:
        - server