version: '3.9'
services:
  redis:
    extends: 
      file: ../Redis/docker-compose.yml
      service: redis
      
  harvest-service:
    extends:
      file: Harvest-server/docker-compose.yml
      service: harvest-service

  server:
    extends:
      file: Server/docker-compose.yml
      service: server
    depends_on:
        - redis
  
  http-client:
    extends:
      file: HTTPClient/docker-compose.yml
      service: http-client
    depends_on:
        - server

  socketio-client:
    extends:
      file: SocketIOClient/docker-compose.yml
      service: socketio-client
    depends_on:
        - server