version: '3.9'
services:
  harvest-service:
    extends:
      file: Harvest-server/docker-compose.yml
      service: harvest-service

  api-gateway:
    extends:
      file: ../api-gateway/docker-compose.yml
      service: api-gateway
    
  server:
    extends:
      file: Server/docker-compose.yml
      service: server
    depends_on:
      - api-gateway
  
  http-client:
    extends:
      file: HTTPClient/docker-compose.yml
      service: http-client
    depends_on:
      - api-gateway
      - harvest-service

  socketio-client:
    extends:
      file: SocketIOClient/docker-compose.yml
      service: socketio-client
    depends_on:
      - api-gateway
      - harvest-service