version: '3.9'

services:
  http-producer:
    container_name: http-producer
    build: 
      context: .
    ports:
      - target: 3000
        published: 30002
        protocol: tcp
        mode: host
