version: '3.9'

services:
  http-client:
    container_name: http-client
    build: 
      context: .
    ports:
      - target: 3000
        published: 30002
        protocol: tcp
        mode: host
