version: '3.9'

services:
  redis:
    image: redis:alpine
    networks:
        - overlay
    deploy:
      replicas: 6
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  server:
    container_name: server
    depends_on:
      - redis
    build: 
      context: ./Server
    networks:
        - overlay
    ports:
      - target: 3000
        published: 3002
        protocol: tcp
        mode: host

  
  api-gateway:
    container_name: api-gateway
    depends_on:
      - server
    build: 
      context: ../gateway
    networks:
        - overlay
    ports:
      - target: 3000
        published: 3001
        protocol: tcp
        mode: host

  client:
    container_name: client
    depends_on:
      - server
      - redis
    build: 
      context: ./Client
    networks:
        - overlay
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host



networks:
  overlay: