version: '3.9'

services:
  server:
    container_name: server
    #depends_on: 
    #  - redis
    build: 
      context: ./Server
    networks:
        - overlay
    ports:
      - target: 3000
        published: 3002
        protocol: tcp
        mode: host

  
  api-gateway:
    container_name: api-gateway
    depends_on:
      - server
    build: 
      context: ../gateway
    networks:
        - overlay
    ports:
      - target: 3000
        published: 3001
        protocol: tcp
        mode: host

  client:
    container_name: client
    depends_on:
      - server
    build: 
      context: ./Client
    networks:
        - overlay
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host



networks:
  overlay: