version: '3.9'

services:
  socketio-client:
    container_name: socketio-client
    build: 
      context: .
    ports:
      - target: 3000
        published: 30003
        protocol: tcp
        mode: host
